% Filename: DoMovie.m
% Description: Video of GRID generated by Afg_Kernel_Estimation.m
% 
% Requires: ../Shapefiles
%           ../Common_functions
%           AWD_Nonparametric_smooth.mat (contains GRID)
%           ../AfghanDataAllDay.mat (AWD in Matlab format)
%           IN.mat (digitised interior mask of Afghanistan)
%           mpgwrite (available online)

clear all
close all
addpath('../Common_functions')

% Load shapefiles
Countrybounds = shaperead('../Shapefiles/admin1_poly_32.shp','UseGeoCoords',true);
Provbounds = shaperead('../Shapefiles/admin2_poly_32.shp','UseGeoCoords',true);

% Load nonparametric intensity map
load('AWD_Nonparametric_smooth')

% Reverse warping (this going back and forth is not necessary...)
strue1 = s1./scale(1) + shift(1);
strue2 = s2./scale(2) + shift(2);
[s1true,s2true] = meshgrid(strue1,strue2);

%---------------------------------------
% MOVIE OF INTENSITY
%---------------------------------------
FRMult = 6; %Repeat frames for slower speed
nframes = size((size(GRID,3)-1)*FRMult);  %Defines length of animation
M = moviein(nframes); close
c = flipud(hot(1024));
c(end-120:end,:) = [];
count=1;

screen_size = get(0, 'ScreenSize');
f1 = figure;
set(f1, 'Position', [0 60 screen_size(3)-200 screen_size(4) ] );
weekinter = 365/7;
% IN = inpolygons(s1true(:),s2true(:),Countrybounds.Lon',Countrybounds.Lat');
load('IN','IN');

for i = 2:size(GRID,3)-1
    DrawAFGmap
    i
    hold on
    myintensity = 6.6*GRID(:,:,i); % The 6.6 is because the intensity was estimated on a warped surface (2.2*3 = 6.6)
    myintensity(IN == 0)= 0.001; % Lower bound for plotting purposes
   
    % log plot
    surfm(s2true,s1true,log10(myintensity))
    shading interp

    myscale = [1 50];
    caxis(myscale)
    colormap(c);
    h=colorbar;
    ticks_wanted=unique([1,10,20,30,50]);
    caxis(log10(myscale))
    set(h,'YTick',log10(ticks_wanted));
    set(h,'YTickLabel',ticks_wanted);
    set(h,'FontSize',20)
    set(h,'Position',[0.94,0.1,0.02,0.8])
    
    yearstr = num2str(2004+floor(i/weekinter));
    [temp,monthstr] = month((i - round(weekinter*floor(i/weekinter)))*7);
    mystr = ['\bf ',monthstr,' ',yearstr];
    textm(38.4,61,mystr,'FontSize',20);
    points = [spikeAllWeekData(i).Coords(:,1)/scale(1)+shift(1) spikeAllWeekData(i).Coords(:,2)/scale(2) + shift(2)];
    Inpoints = inpolygon(points(:,1),points(:,2),Countrybounds.Lon',Countrybounds.Lat');
    if sum(Inpoints == 0) > 0
        points(Inpoints == 0,:) = [];
    end
    plot3m(points(:,2),points(:,1),repmat(1e10,length(points),1),'g.','Linewidth',0.5)
    
    
    setm(ax,'Grid','on','Frame','on','meridianlabel','on','parallellabel','on','FontSize',14)
    %Plot grid
    set(gca,'FontSize',20)
    xlabel('Longitude','FontSize',25)
    ylabel('Latitude','FontSize',25)
%     text(0.15,0.5,'Expected report counts per week per 10,000km^2','rotation',90,'FontSize',20)
    text(-0.165,0.5,'Expected report count per week per degree^2','rotation',90,'FontSize',16)
    
    set(gcf,'color',[1,1,1])
    
    hold off
    clear Editedframe Thisframe
    
    Thisframe = getframe(gcf);
    Editedframe = Thisframe;
    
    % Shift frame horizontally
    Editedframe.cdata(:,:,1) = circshift(Thisframe.cdata(:,:,1),[0,-50]);
    Editedframe.cdata(:,:,2) = circshift(Thisframe.cdata(:,:,2),[0,-50]);
    Editedframe.cdata(:,:,3) = circshift(Thisframe.cdata(:,:,3),[0,-50]);
    M(:,count:count+FRMult-1)=Editedframe;
%     mov=addframe(mov,Editedframe); % adds the frame into mov  

    count = count+FRMult;
    pause(0.1)
    colorbar off
end
save movie.mat M

% Save mpg
mpgwrite(M,jet,'./KEIntensity.mpg'); % Convert the movie to MPEG format 

